### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by yazinsai** [TigerWolf/e24PaymentPipe-php#1]
Always fails with the error 'Failed to make connection'

**Comment by TigerWolf** [comment]
Are you specifying a port other than the default? Can you provide more information about what you are trying to do and the code you are using so I can have a look at what might be causing the issue.

**Comment by yazinsai** [comment]
No, I'm actually using this on port 80 on my local machine. I use Apache v2.4.2 and PHP 5.3.14.
I tried uploading this to my shared host and get the same error message.

I'm trying to process a payment through the ACI payment platform. I have the CGN located in the /resources/ folder.

Here's the code I'm using:

``` php
<?php
require_once('e24PaymentPipe.inc.php');
$payment = new e24PaymentPipe;

$payment->setErrorUrl("https://mydomain.com/response.php"); // where mydomain.com is my actual domain
$payment->setResponseURL("https://mydomain.com/response.php"); // where mydomain.com is my actual domain

$payment->setLanguage("ENG");
$payment->setCurrency("048"); //BHD
$payment->setResourcePath('/resources/');
$payment->setAlias("MYALIAS");
$payment->setAction("4"); // 1 = Purchase

$payment->setAmt("10.00");
$payment->performPaymentInitialization();

if (strlen($payment->getErrorMsg()) > 0) {
  echo $payment->getErrorMsg();
}else{ 
  header('Location: ' . $payment_id = $payment->paymentPage . '?PaymentID=' . $payment->paymentId);
}
?>
```

**Comment by TigerWolf** [comment]
I don't have a testing environment in front of me at the moment and my version of this code works fine. I would put in some debugging statements to see what is going on. The error is being raised on line 466 - so I would start there and work back up. If you need any help with this let me know.

**Comment by yazinsai** [comment]
What documentation did you use to put this together; do you have a reference I can use?

I've done the troubleshooting and it looks like it fails in extracting the URL from the .xml file after extracting it from the cgn

**Comment by TigerWolf** [comment]
There is barely any documentation available on this at all. If you stop the script from deleting the XML file - you can view the contents on the file system. 

This is a port from an original Java implementation of this. There is also a ruby and a python version. If you can get it working with the Java version then it will definitely work with the php one. The payment gateway would have provided a Java version and also documentation for this.

**Comment by nitsuasd** [comment]
Hi TigerWolf, FloatingRock

I am having the same issue as floating rock. Looking at your code it looks like you are from Bahrain and probably having this issue with Benefitco. I have been stumped all day with the same issue.

Have you found a solution as yet?

Thanks for any help.

**Comment by TigerWolf** [comment]
Try this code out and let me know what the debug string echos:

http://collabedit.com/49rwj

https://gist.github.com/3858263

**Comment by nitsuasd** [comment]
The debug string below.
Debug ---------- PaymentInitHTTPServlet: 1349783739 ----------Failed to make connection:

**Comment by TigerWolf** [comment]
I would need to see your CURL log and the interactions between the script and the server. It could be an issue with DNS lookup or SSL or auth issues with the payment gateway.

**Comment by nitsuasd** [comment]
Hi TigerWolf

I had discussed with another guy who works on the Banking System for one of
the largest regional banks. His name is Burkhan Khalid. He informed me that
the cgn file format has been changed and that it would take some time to
fix the problem. Since I needed some to complete project I used an
additional TomCat Server to handle the Java request.

If you eventually put out an update or if I could help in anyway, do let me
know.

Regards
Austin

**Comment by TigerWolf** [comment]
If I could see the CGN file then I would be able to update this to make it work. There is sensitive data in the CGN files so if you could replace this with dummy data then this would help me greatly in getting this php port to work for all versions of the CGN file.

**Comment by nitsuasd** [comment]
HI

I would definitely be willing to help, can you let me know where i need to
add the dummy data as in which variables. Also what editor do I use?

Austin

**Comment by TigerWolf** [comment]
The CGN file is encrypted, it contains a username and password. If you change this information to different values then I wont be able to use the passwords. You can use the php script to unencypt the file, you will just need to comment out the part of the code where it deletes the file after use.

**Comment by adeshsuryan** [comment]
Hi TigerWolf,
                     I am getting error , when we are trying to Connect KNET payment getaway.

---------- PaymentInitHTTPServlet: 1356850079 ----------
About to create the URL to: https://www.knetpaytest.com.kw:443/CGW302/servlet/PaymentInitHTTPServlet
About to create http connection
Created connection
about to write DataOutputSteam
after DataOutputStream
Received RESPONSE: ERROR - CGW000166-Tran Portal Pwd Hash Invalid"

![error_image](https://f.cloud.github.com/assets/887994/37238/7d3a2d1c-5412-11e2-876f-d5f270e149b6.png)

**Comment by firoz110** [comment]
Hello TigerWolf, 

I am getting this error when I try to accept payment via KNET -
["rawResponse"]=> string(46) "ERROR - CGW000166-Tran Portal Pwd Hash Invalid"

There is not much documentation available. Do you have any idea about this?

Thanks.

**Comment by TigerWolf** [comment]
I suspect KNET has changed the way that they do authentication. There is nothing much I can do as I no longer work at the company that did integration with KNET so no longer have any contacts there. I suspect that they have changed the way they use the username/password. In order to help out and test I would need a test cgz and client ID.

@adeshsuryan Looks like your errorURL is incorrect. It needs to be a url not a directory. like http://mydomain.com/error Do you also have your resource file in your resource directory?

**Comment by firoz110** [comment]
Thanks TigerWolf for your reply. 

I cannot share the original files .cgz file and client ID as it belongs to client. Also I cannot add a dummy client ID and password because the file is encrypted and I do not know which algorithm to use to decrypt it and change data then encrypt it again and send you.

**Comment by yazinsai** [comment]
Ok - found out the issue (finally) in the `parseSettings()` function. Benefit uses a different format (it doesn't wrap the data in any XML tags). Might make more sense to just fork it and make the changes so your repo doesn't get poisoned with multiple formats.
